### ISSUE TITLE
Not in scope: type constructor or class ‘MonadFail’

### ISSUE THREAD

**Issue by nomeata** [taruti/haskell-hex#3]
Hi!

Your package fails to build on recent GHCs: http://hackage.haskell.org/package/hex-0.2.0/reports/

**Comment by Zachaccino** [comment]
Building the library works on ghc8.8.4, but not working on ghc8.6.4.

If you need to use it urgently, you can try that. Otherwise, might need to wait for a fix.

**Comment by taruti** [comment]
Oh well I gues this is due to the GHC 8.8 compatibility patches.

Feel free to do a PR with e.g. CPP to handle this with different versions of GHC?

**Comment by emberdart** [comment]
0.2.0 should be better! It uses MonadFail properly.
